package gateway

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// FilesystemReplayStore is a ReplayStore that writes session
// recordings to a local directory tree mirroring the canonical
// ReplayKey path. It is the default store wired into the pam-gateway
// dev binary when no S3 endpoint is configured — production
// deployments install the S3-backed store from Milestone 7.
//
// The on-disk layout matches the storage key shape so the same
// session-id resolves the blob regardless of which backend the
// audit service queries:
//
//	{Root}/sessions/{session_id}/replay.bin
//
// All operations are best-effort: the recorder's Close path returns
// the underlying error so the caller can decide whether to drop the
// blob silently (recommended) or surface it to the operator.
type FilesystemReplayStore struct {
	root string
}

// NewFilesystemReplayStore returns a store rooted at root. root is
// created if it does not exist. An empty root is rejected so a
// misconfigured deployment cannot accidentally write into the
// process CWD.
func NewFilesystemReplayStore(root string) (*FilesystemReplayStore, error) {
	if root == "" {
		return nil, errors.New("gateway: NewFilesystemReplayStore: empty root")
	}
	if err := os.MkdirAll(root, 0o750); err != nil {
		return nil, fmt.Errorf("gateway: mkdir replay root %q: %w", root, err)
	}
	return &FilesystemReplayStore{root: root}, nil
}

// PutReplay writes the replay blob for sessionID under
// {Root}/sessions/{session_id}/replay.bin. The destination directory
// is created on demand so callers do not need to pre-provision it.
//
// The file is written atomically via a temp file + rename so a
// concurrent reader (the audit service's signed-URL flow) cannot
// observe a partial blob mid-upload.
//
// Path-traversal defence-in-depth: session IDs are generated by the
// trusted ztna-api as ULIDs and never contain "../" / absolute path
// markers in practice. We nevertheless re-validate the resolved
// destination against f.root after filepath.Join so a compromised
// (or future-refactored) control plane that returns a malicious
// session id ("..", "foo/../../etc/...", "/etc/cron.d/x") cannot
// escape the configured replay root.
func (f *FilesystemReplayStore) PutReplay(ctx context.Context, sessionID string, r io.Reader) error {
	if f == nil {
		return errors.New("gateway: FilesystemReplayStore is nil")
	}
	if sessionID == "" {
		return errors.New("gateway: PutReplay: empty session id")
	}
	if r == nil {
		return errors.New("gateway: PutReplay: nil reader")
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	dst, err := f.resolveReplayPath(sessionID)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o750); err != nil {
		return fmt.Errorf("gateway: mkdir replay dir: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(dst), "replay-*.bin.partial")
	if err != nil {
		return fmt.Errorf("gateway: create temp replay file: %w", err)
	}
	tmpName := tmp.Name()
	// Best-effort cleanup if anything below this point fails. If
	// the rename succeeds the temp file no longer exists so Remove
	// is a harmless no-op.
	defer func() {
		_ = os.Remove(tmpName)
	}()
	if _, err := io.Copy(tmp, r); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("gateway: write replay body: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("gateway: close replay file: %w", err)
	}
	if err := os.Rename(tmpName, dst); err != nil {
		return fmt.Errorf("gateway: rename replay file: %w", err)
	}
	return nil
}

// Root returns the directory the store is rooted at — used by tests
// and the audit service to compute relative replay paths.
func (f *FilesystemReplayStore) Root() string {
	if f == nil {
		return ""
	}
	return f.root
}

// resolveReplayPath joins sessionID against the store root and
// verifies the result stays under the root. Returns an error when
// the session id contains path-traversal characters or the joined
// path escapes the root — defence-in-depth against a control plane
// that hands us a malformed id. Session ids in production are
// ULIDs (Crockford base32, fixed 26 chars), so this only ever
// rejects malformed input.
//
// Two layers of defence:
//
//  1. Reject session ids that contain any path separator (`/` or
//     the platform separator) or that equal `.` / `..`. Any of
//     these would let the joined path land in a sibling directory
//     of `{root}/sessions/` (e.g. `sessions//etc/passwd` cleans to
//     `sessions/etc/passwd`, still inside the root but not in the
//     expected per-session directory).
//
//  2. After Clean+Join, double-check the result is contained in
//     the root via filepath.Rel — catches edge cases the first
//     check might miss (URL-encoded separators, future format
//     changes to ReplayKey).
func (f *FilesystemReplayStore) resolveReplayPath(sessionID string) (string, error) {
	if sessionID == "" {
		return "", errors.New("gateway: resolve replay path: empty session id")
	}
	if strings.ContainsAny(sessionID, "/\\") || strings.ContainsRune(sessionID, filepath.Separator) {
		return "", fmt.Errorf("gateway: session id %q contains a path separator", sessionID)
	}
	if sessionID == "." || sessionID == ".." {
		return "", fmt.Errorf("gateway: session id %q is a path navigation token", sessionID)
	}
	cleanRoot := filepath.Clean(f.root)
	dst := filepath.Clean(filepath.Join(cleanRoot, ReplayKey(sessionID)))
	// filepath.Rel returns a path that starts with ".." when dst is
	// not contained in cleanRoot — that's the canonical containment
	// check. The cheaper string-prefix variant misses edge cases
	// like "/var/replay" vs "/var/replay-evil".
	rel, err := filepath.Rel(cleanRoot, dst)
	if err != nil {
		return "", fmt.Errorf("gateway: resolve replay path: %w", err)
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("gateway: replay path %q escapes root %q", dst, cleanRoot)
	}
	return dst, nil
}
