package handlers

import (
	_ "embed"
	"net/http"

	"github.com/gin-gonic/gin"
)

// swaggerJSON is the OpenAPI 3.0 spec generated by
// scripts/generate-swagger.sh from the annotated handlers in this
// package. The file is embedded at build time so the API surface is
// self-describing without a separate static file server.
//
//go:embed swagger.json
var swaggerJSON []byte

// swaggerYAML is the YAML rendering of the same spec, served for
// consumers that prefer the multiline format (e.g. some Swagger UI
// distributions, code generators).
//
//go:embed swagger.yaml
var swaggerYAML []byte

// SwaggerHandler serves the embedded OpenAPI 3.0 spec as JSON. Use
// /swagger or /swagger.json. The spec is regenerated by
// scripts/generate-swagger.sh whenever the public API surface changes
// (cross-cutting criterion in docs/internal/PHASES.md).
func SwaggerHandler(c *gin.Context) {
	c.Data(http.StatusOK, "application/json; charset=utf-8", swaggerJSON)
}

// SwaggerYAMLHandler serves the same OpenAPI spec as YAML. Use
// /swagger.yaml.
func SwaggerYAMLHandler(c *gin.Context) {
	c.Data(http.StatusOK, "application/yaml; charset=utf-8", swaggerYAML)
}
